sudo: false
language: ruby
rvm:
    - 2.4.1
branches:
  only:
  - source
script: make deploy
before_install:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_45185b495e19_key -iv $encrypted_45185b495e19_iv -in openfalcon_rsa.enc -out openfalcon_rsa -d
- chmod 600 openfalcon_rsa
- ssh-add openfalcon_rsa
env:
  global:
  - secure: mqAwLqCewVofEqGAvc/mtwZunrFIDL54RwZo5+vt6cph2GafYxr34aEWJT7bSQyr5C5FFUa6Wc5dkLvEjDHZ+lvxNvKdR1E1WTs1iHEDNGKX34AZYzH/7wfwBUgoUgHOrEw6KKFzN47IK02ROLfPqSO+wEEntnI3wxOVnBRXcgQSTrwEn+oyJTZJuiGrkdHEIhFUgatStOqzgNpyKwOTZ6wq5x7rtfHLmgC7b5zpju6xP8J++Z76oww5DtRjEHszdaKdFMO9wPpSGP0pwRaBz/a7BDpCNf3BfII2NnTvATZLGUHA1TOtqn6OZOXjSxws6Bdr1Cwj7s7iHcPtR58y/ORXKLL/SUuSYOLYgblDHVfwTtfRdcndptX65tSQ5kf2d0y9NLvjzv/SpuNquDV0gM6BEd8G4YXIM0RZ+X1cju4iLs4d0sN7PNRZQFae/6MwAXRft+pbr9Qj8NfUMkJrbN9ooI1JRbJlQaKhgtmSm2m85K35fGJWHRx5yYZxjHNctVKPNgjCjtnPueRpav0CXygSFj2wAqYX1XH1d7mfGuWRomG3aTSY8iE+hu76KwWA7yLdJO4JX3wxM+8ysQkuxIOy42+rZlMK3JsSfa5VfHz9RUBcfpuDAqPOiSHZ/oESOrUMrxVbtFfUOYCf77nh7mv91xsYrWGzFMYx8CxsaDQ=
